<?php
/**
 * Implements hook_wysiwyg_editor_settings_alter().
 *
 * See https://drupal.org/node/1956778
 * See https://drupal.org/node/1979042#comment-7633733
 * See http://fuseinteractive.ca/blog/wysiwyg-module-ckeditor-taming-beast
 */
function cpmcri_wysiwyg_editor_settings_alter(&$settings, $context) {
  if ($context['profile']->editor == 'ckeditor') {

  }
}
function ckeditor_custom_wysiwyg_editor_settings_alter(&$settings, $context) {

  // The $context variable contains information about the wysiwyg profile we're using
  // In this case we just need to check that the editor being used is ckeditor

  if ($context['profile']->editor == 'ckeditor') {

    // Allow users to add classes to src (templates require this)
    $settings['allowedContent'] = TRUE;

    // Add the javascript file that will enable the webkit-span-fix
    // See https://github.com/RomanMinkin/webkit-span-fix
    $settings['customConfig'] = base_path() . drupal_get_path('module', 'ckeditor_custom') .
                                '/ckeditor_custom_config.js';
  }
}
